name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: self-hosted
    steps:    
      - uses: actions/checkout@v4
      
      - name: Login to DockerHUB 
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
          
      - name: voteApp Build, tag, and push image to DockerHUB  
        env:
          IMAGE_NAME: vote-app
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./vote
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - name: voteApp Build, tag, and push image to DockerHUB  
        env:
          IMAGE_NAME: worker-app
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./worker
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - name: voteApp Build, tag, and push image to DockerHUB  
        env:
          IMAGE_NAME: result-app
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG ./result
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Update GitOps Values Vote
        env:
            IMAGE_TAG: ${{ github.sha }}
        run: |
            sed -i "" "s/tag: v1/tag: $IMAGE_TAG/" ./gitops/vote/values.yaml
            
      - name: Update GitOps Values Worker
        env:
            IMAGE_TAG: ${{ github.sha }}
        run: |
            sed -i "" "s/tag: v1/tag: $IMAGE_TAG/" ./gitops/worker/values.yaml

      - name: Update GitOps Values Result
        env:
            IMAGE_TAG: ${{ github.sha }}
        run: |
            sed -i "" "s/tag: v1/tag: $IMAGE_TAG/" ./gitops/result/values.yaml

      - name: Helm Upgrade
        run: |
          helm ls
          helm upgrade --install vote-app-chart -n default ./gitops/chart
      
    
    
